### ISSUE TITLE
What’s that

### ISSUE THREAD

**Issue by Galixte** [marttiphpbb/phpbb-ext-communitycurrencies#1]
Hi @marttiphpbb,

sorry, but i don’t understand the goal of your extension. Is a simulation ?

**Comment by marttiphpbb** [comment]
Hello Galixte,
The goal is that your board can be turned into a platform for a LETS or Time Banking group. (see wikipedia for explanation). The extension introduces a community currency that can be used for exchanging goods and services between people. Every member of the board gets an account. The self-created currency is closed; it is only valid between members of the group and not exchangeable with other currencies. 
It's only in early development at the moment.

**Comment by Galixte** [comment]
Thanks.
